site_name: રાસ-ગરબા સંગ્રહ
site_author: Paresh Adhia
theme:
  name: material
  logo: assets/aum.svg
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.footer

copyright: Copyright &copy; 2013 - 2024 Charlotte Navratri Group

extra:
  generator: false

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: True
